declare class DummyVariable {}

/**
 * This should be generated by the experience engine vfs compiler based on the latest user defined types
 * all other types reference these maps by id
 */
export declare type ComponentsMap = Record<string, ComponentScript>;

export declare type SystemsMap = Record<string, SystemScript>;

export declare type VariableTypeById = Record<string, string>;

export declare type SystemIdType = "someUniqueId" | "someUID";
export declare type ComponentIdType = "someUniqueId" | "someUID";
export declare type StageIdType = "someUniqueId" | "someUID";
export declare type SpriteIdType = "someUniqueId" | "someUID";
export declare type VariableIdType = "someUniqueId" | "someUID";

// these are the ids users name sprite instances with.. not the sprite document ids / document unique ids
export declare type SpriteUniqueIdTypes = string;
